# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 788a4d61cb670f8d0a59d3a565cc5c4ac1734d4e26871d353e226afb2d037a78cbc1986dcc6adc3b3fc351cab30a0b2e72cc93f25bbe31cbcaf4d06d423e8a05

test:
  secret_key_base: 65c885f029158f721fa6996c08d3e51791cf7a01ed2d6c1d986298e7e51f9c5cf9f4181c990d6fe20cd72b4ca769b9ccd1dd196e18c874784ea4cc309c9c1218

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
